name: boteco_pro
description: Aplicação Flutter para o sistema Boteco_PRO
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  flutter:
    sdk: flutter
  http: ^0.13.4

flutter:
  uses-material-design: true